name: Clang Tidy and Clang Format

on: [push]

jobs:
  cleanup:
    name: Clang Tidy and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Cmake
        uses: lukka/get-cmake@v3.21.2

      - name: Set up Clang
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install -y clang-12 clang-format-13 clang-tidy-13
          sudo update-alternatives --install /bin/clang-tidy clang-tidy /bin/clang-tidy-13 100
          sudo update-alternatives --install /bin/clang-format clang-format /bin/clang-format-13 100

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=on

      - name: Clang Tidy
        run: |
          cd build
          cmake --build . --target clangtidy

      - name: Clang Format
        run: |
          cd build
          cmake --build . --target clangformat

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Clang Tidy And Format"
          title: "Clang Tidy And Format"
          delete-branch: true
