name: Clang Tidy and Clang Format

on: [push]

jobs:
  cleanup:
    name: Clang Tidy and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Cmake
        uses: lukka/get-cmake@v3.21.2

      - name: Set up Clang
        run: sudo apt install -y clang-12 clang-format-12 clang-tidy-12

      - name: Configure CMake
        cc: "clang-12"
        cxx: "clang++-12"
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Clang Tidy
        run: |
          cd build
          cmake --build . --target clangtidy

      - name: Clang Format
        run: cmake --build . --target clangformat

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Clang Tidy And Format"
          title: "Clang Tidy And Format"
          delete-branch: true
