name: Clang Tidy and Clang Format

on: [ push ]

jobs:
  cleanup:
    name: Clang Tidy and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Cmake
        uses: lukka/get-cmake@v3.21.2

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 14
          platform: x64

      - name: Verify up Clang
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends clang-format-14 clang-tidy-14
          
          sudo update-alternatives --install /bin/clang-tidy clang-tidy /bin/clang-tidy-14 100
          sudo update-alternatives --install /bin/clang-format clang-format /bin/clang-format-14 100
          
          echo "Clang Version:"
          clang --version
          echo "Clang++ Version:"
          clang++ --version
          echo "Clang-Format Version:"
          clang-format --version
          echo "Clang-Tidy Version:"
          clang-tidy --version

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=on

      - name: Clang Tidy
        run: |
          cd build
          cmake --build . --target clangtidy

      - name: Clang Format
        run: |
          cd build
          cmake --build . --target clangformat

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Clang Tidy And Format"
          title: "Clang Tidy And Format"
          delete-branch: true
